### ISSUE TITLE
need shadow3 for blicon project

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#194]
The glicon project needs shadow3. Fixing it to compile with the latest gfortran seems impractical. Could we do a special compile for it using an older compiler. Maksim mentioned using conda as a possibility.  

Both Boaz and Nick would like to use shadow3 with their juptyer notebooks.

**Comment by robnagler** [comment]
There is a fork that supposedly works. I'll look into it.

We don't want to mess with Conda on Fedora, rather we can get different versions of compilers via dnf.

**Comment by robnagler** [comment]
I just tried to `pip install shadow3` with a regular install of `xraylib` in py3. It was missing `libgfortran.so.4`, which I found in compat-libgfortran-41 on Fedora 29. But, unfortunately, they forgot to build [libquadmath](https://bugs.centos.org/view.php?id=15241), and `sqrtq` (float 128) is missing. 

shadow_bind_python.c is using deprecated and some deleted numpy interfaces:

```txt
src/c/shadow_bind_python.c:71:118: error: ‘NPY_CARRAY’ undeclared
src/c/shadow_bind_python.c:71:129: error: ‘NPY_OWNDATA’ undeclared
```

NPY_OWNDATA was introduced in 1.6 and renamed to NPY_ARRAY_OWNDATA in 1.7.

Therefore, it's not so easy to integrate in a single environment.

One option I'm going to try is building a Fedora 27 docker image with shadow and sirepo in a py3 environment. I think this might be the fastest way to get something going. I don't think it would be possible to run shadow3 in the regular Sirepo container.

We already have a prototype to run different versions of the containers.

We'll need to move getApplicationData into job environment so that this will work. It's got to be outside of the flask server. @moellep unless you can avoid the import of xraylib in the template.

I'll think about this over the weekend, and maybe another idea will work.

**Comment by moellep** [comment]
Looks like replacing xraylib from template.shadow would be easy. It is only used to get a list of material names. That could get removed, put in the schema and validated on the client.

**Comment by robnagler** [comment]
Shadow is working on Fedora 29. I had to recompile gcc-7.5.0 to get one file: libgfortran.so.4. With that, a `pip install shadow3` and a few twiddles to the way shadow is executed, and it works with job_cmd running in py3. The srxraylib isn't needed for the example I used. This looks good:

![Screen Shot 2020-03-03 at 5 58 03 PM](https://user-images.githubusercontent.com/5495179/75834189-937b2000-5d78-11ea-93c2-2115227b7a73.png)

And it matches the output from radiasoft/sirepo:20181207.235238:

![Screen Shot 2020-03-03 at 5 57 51 PM](https://user-images.githubusercontent.com/5495179/75834210-a0980f00-5d78-11ea-85a8-ad6266336a71.png)

@bruhwiler this was a one line change to the curl sirepo command to make this work.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/download/commit/a37edc5a79bcbae0ad69f06fd496e12955918158 and https://github.com/radiasoft/sirepo/commit/a39404d4b07d6845bfc447c12adee2e6428e478e

Still need to reinstall with beamsim, but waiting on @moellep to approve fixes.

**Comment by moellep** [comment]
I've made a few changes to sirepo/shadow and verified all the examples work OK. I've added it back to the list of sirepo apps.
