### ISSUE TITLE
Upgrade HDF5 to avoid a potential issues with HDF5 1.8.20.

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#217]
Running the CapLaser3D simulation (with a 2D geometry) on Jupyter on 16 cores produced a crash with the following error:

```
Fatal error in PMPI_Comm_dup: Other MPI error, error stack:
PMPI_Comm_dup(177)..................: MPI_Comm_dup(comm=0xc40053e9, new_comm=0x7fff656c19e0) failed
PMPI_Comm_dup(162)..................: 
MPIR_Comm_dup_impl(57)..............: 
MPIR_Comm_copy(739).................: 
MPIR_Get_contextid_sparse_group(614): Too many communicators (0/2048 free on this process; ignore_id=0)
```

I've received this error for more than one set of runtime parameters, and @sjcrs recently received a similar error as well.

@sjcrs noted that this error has been seen with our version of HDF5 [elsewhere](https://cgnsorg.atlassian.net/browse/CGNS-109) and that it could be avoided by upgrading to 1.10.5. It's also possible that this is the result of our HDF5 configuration not being thread-safe.

**Comment by robnagler** [comment]
Currently we use the HDF5 packages that come with Fedora 29, which is quite out of date. The best thing would be to update to Fedora 32 so that it would fix this issue without having to build HDF5 ourselves (which is complicated because it integrates with MPI, etc.).  

I created https://github.com/radiasoft/download/issues/131 to track the issue.

**Comment by robnagler** [comment]
Many of the codes are compiling, but still haven't compiled shadow, which is a tricky one. I probably will be at this for another week at this pace.

**Comment by robnagler** [comment]
Done
