### ISSUE TITLE
workspace does not work with youtube

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#220]

**Comment by robnagler** [comment]
Joy. The [google support answer](https://support.google.com/a/answer/9000768) is: 

> ### Limited access is temporary
> You and your users can use all features of YouTube when your domain has cumulatively paid at least USD 100 (or equivalent), and at least 60 days have passed since reaching that payment threshold.
> 
> ### Why is access limited? 
> To keep our systems healthy, we have minimum requirements for Google Workspace accounts to upload videos, add comments, create a channel, and other actions that require being signed into an account. 

I'm closing because there's nothing we can do except run YouTube in a different browser that is not logged in...

**Comment by e-carlin** [comment]
FWIW - I'm late to the game but I added my @radiasoft.net email to the gmail app on ios. YouTube videos wouldn't play on Safari on my phone. Turns out by adding my @radiasoft.net address to the gmail app I became signed in to Google in Safari. Going to google.com in Safari and signing out solved it.
