### ISSUE TITLE
Convey URLs to Mac Mini in conference room

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#268]
We can drop files on the Mac Mini via Air Drop (which works only for Macs). However, we can't convey URLs easily. If you want to join an MS teams meeting, how do you do it? You need a way to put in a URL. Easiest way may be to run a small web server that accepts files and/or URLs and does something smart with them (starts preview, teams, zoom, etc.).

Google Docs could be handled by sharing with a Google user that the Mac Mini is logged into. 

Could also be logged into Slack, since that would be convenient to have meetings.

**Comment by robnagler** [comment]
@gurhar1133 @rorour I would like you to work together on this project. It will help you get familiarized with React and Tornado. 

@rorour I would like to extract some of the Sirepo libraries in such a way that we can use them for this project. I would like it copied into Pykern, because I don't like lots of little repos. (@radiasoft/software please discuss :) Particularly, I would like people to be authenticated in order to use the Mac mini. They will need email-based login the first time, just like Sirepo. 

@gurhar1133 I would like users to be able to login, have a bookmark to the server, and for the server to do smart things with URLs. For example, if they drop a pptx on the web page, it should up load it. If they drop a URL, it should be opened on Chrome on the Mac Mini (not the user's browser).

For both of you (with other people's help), we will use web sockets to communicate between React and Tornado.

There's a lot here, but it is green field so it's a bit easier.

Also, you can prototype a simple solution, e.g. drop a URL on the web page and it opens the page on the Mac mini (which also needs a name).

You should get together to plan out this project and create issues.

**Comment by e-carlin** [comment]
I'm sure you've thought about this more than I have so I'm hesitant to say anything. But here it goes: what about putting a hub behind the tv with the hdmi, camera, and mic all connected to it? We then run a wire from the hub to the conference table. Someone in the meeting plugs their computer into the hub and joins the call. We get access to the tv, camera, and mic and it all works in a way people are familiar with (I think). I think an added benefit of this system is that folks w/o a mac can connect to this system and present from the comfort of their own computer. For example, if myself and a windows users were in the conference room to discuss something the windows person could just plug in and show me what they want to (maybe from a native app that only they have installed). Otherwise we'd have to start a call, get the mac mini to join it, then they would present from their computer through the call onto the screen.

**Comment by robnagler** [comment]
Maximum cable length on USB-c is 9ft. A longer cable might work, but there's a lot data going over that wire at 4k bidirectional.

You are certainly welcome to try it. Indeed, you are welcome to take over the project while still doing your other tasks. :)

You'll need a bluetooth usb adapter for the Jabra. You could use a Logitech/Microsoft for the mouse/keyboard.

**Comment by robnagler** [comment]
@gurhar1133 @rorour let's wait on this.

**Comment by e-carlin** [comment]
Ok, I'll do a little research and try next week.

**Comment by robnagler** [comment]
Current solution is fine.
