### ISSUE TITLE
libboost not found in Sirepo or GPU Jupyter

### ISSUE THREAD

**Issue by mkilpatr** [radiasoft/devops#270]
Cannot locate the libboost_python37.so.1.68.0 in Sirepo jupyter or GPU jupyter. I have added the LD_LIBRARY_PATH that points to this file, but it is not found. I've attached the smallest example of the code that produces the error along with the error from jupyter.;

import os, io, sys
sys.path.append("/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/")
os.environ['LD_LIBRARY_PATH'] = '/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/:' + os.environ['LD_LIBRARY_PATH']
from server.app.models_old import EventToVoxelConverter

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_23718/3785900069.py in <module>
      2 sys.path.append("/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/")
      3 os.environ['LD_LIBRARY_PATH'] = '/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/:' + os.environ['LD_LIBRARY_PATH']
----> 4 from server.app.models_old import EventToVoxelConverter

~/jupyter/StaffScratch/mkilpatr/ndviz/rsiviz/rsiviz/server/app/models_old.py in <module>
----> 1 import openvdb as vdb
      2 import numpy as np
      3 import itertools
      4 import math
      5 import pickle as pkl

~/.pyenv/versions/py3/lib/python3.7/site-packages/openvdb/__init__.py in <module>
     21         raise ImportError(__msg)
     22 
---> 23 from pyopenvdb import *

ImportError: libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory

**Comment by e-carlin** [comment]
@mkilpatr unfortunately pyopenvdb is hard to use and you’re bumping up against this. Here’s what’s going on:

When pyopenvdb is installed it brings in the pyopenvdb.so (and other so’s). That file needs to exist for everything to work. But, this file is installed in /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/ which is not somewhere on LD_LIBRARY_PATH. So, they tell you to add that path to LD_LIBRARY_PATH which you are doing. The problem is that LD_LIBRARY_PATH is read when the python interpreter is started so setting it inside of a script/notebook is too late.

For scripts you can manually configure the LD_LIBRARY_PATH before starting python. For example,  `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/ python <my-script>.py`

For notebooks I’m still coming up with a good solution. Everything I’ve done so far is causing the kernel to die with no indication of why…

Another route you could take is using a different library than pyopenvdb. Maybe there is another vdb library that doesn't have this problem.

**Comment by mkilpatr** [comment]
Thank you @e-carlin. I was able to get a small work around. I added a preprocessing step to use the voxel code (which requires the pyopenvdb.so packages) to generate the np_grid and save it as a csv file. I now can use a jupyter notebook with the other data packages to import, clean, and run ML methods. 

This seems to be ok for now. It is just another separate step in an evolving framework.

**Comment by robnagler** [comment]
We could build a pyopenvdb installer. I assume it is small.

**Comment by robnagler** [comment]
done
