### ISSUE TITLE
20230225 radiasoft data repo

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#279]
We need a repo separate from sirepo which can store large datafiles for example simulations. cloudmc has large geometry files, and this PR has a cloudmc.data_storage_url feature_config param.

https://github.com/radiasoft/sirepo/pull/5478/files#diff-598e66cc4328747b2cc1a41a8760a88dc382424cbf26451f36b53b763fd6971f

**Comment by robnagler** [comment]
https://github.com/radiasoft/sirepo-data-cloudmc is for cloudmc only. When you get data, you will need to copy *their* license (not ours) into this repo. Include a README that explains where you got the data from. Put all the files at the top level. If any of the files are larger than 100MB, we have to use Git LFS. We should avoid storing these files in lib dirs. Ideally, we'd add this repo (maybe call it sirepo-lib-cloudmc?) to the list of places to download. It currently searches two. Perhaps this could be a parameter in sim_data for the code that says there is an external repo for library files.

Of course, we don't want to leave them lying around in run dirs either so even if the simulation fails, we should clear these files. 

One problem we will have is downloading form GitHub without the API. GH has aggressive caching so we use the API for installers. We can't do this for sirepo, because we aren't authenticated, and GH restricts API accesses, but not raw downloads. 

These are all separate tasks, and cloudmc is not on prod so please create issues for them. For now, this can be a simple download in template.cloudmc.
