### ISSUE TITLE
Synergia2 'devel' branch doesn't build inside RadiaSoft containers

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#37]
The official Synergia build system doesn't work inside our containers.

I know some sort of fix is being used to make this work for Synergia installation when the containers are built.

RadiaSoft personnel need to be able to clone and build the latest version of Synergia2.

Is the fix documented somewhere?
Even better, can we communicate with the Synergia development team to make the fix unnecessary?
Presumably the OS being used in our containers is sufficiently 'standard' that the Synergia team will want to support it?

**Comment by robnagler** [comment]
The build system works. You can say, for example,

curl radia.run | bash -s code synergia

This is the same used inside the container.  I'm building a new container
now.

**Comment by bruhwile** [comment]
Thanks, Rob.

I verified the command works. This is great.

It appears that source and build files are put into /var/tmp/.../ and then get cleaned up afterwards.

I created this issue, because I wanted to git clone the Synergia repository and obtain a development environment. The Synergia build process failed before even the main source directories were pulled from the git repository, so I couldn't even see the source code, much less compile  it.

This is not a priority for now, so I'll close the issue, but it seems strange that the native Synergia build system fails inside our container...

**Comment by robnagler** [comment]
Just to follow up:

> I verified the command works. This is great.

It appears that source and build files are put into /var/tmp/.../ and then get cleaned up afterwards.

I created this issue, because I wanted to git clone the Synergia repository and obtain a development environment. The Synergia build process failed before even the main source directories were pulled from the git repository, so I couldn't even see the source code, much less compile it.

This is not a priority for now, so I'll close the issue, but it seems strange that the native Synergia build system fails inside our container...
