### ISSUE TITLE
github install channels

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#59]
Right now we aren't tagging commits in GitHub. Even if we tagged them with versions, it would be uninteresting, because we really want a consistent install channel.

I don't really have a solution for this right now, just noting that we are installing from master on GitHub unless we know that master is unreliable. With the addition of dynamic customizations to all Jupyter containers, we will probably need to start marking commits or keeping a commit list.

**Comment by elventear** [comment]
I think we should use branches, each distinct branch represents a channel, and there is a code-flow model where code is promoted between channel using git merges.  

In this model new code would flow upstream (alpha->beta->prod) manually when we believe the code has received the amount of scrutiny necessary to be promoted to the next channel. Fixes (bugs) would follow downstream. 

This is a modified [git-flow](http://nvie.com/posts/a-successful-git-branching-model/), where instead of having two branches we have three.

See also:
1. [Comparing git workflows](https://www.atlassian.com/git/tutorials/comparing-workflows)

**Comment by robnagler** [comment]
I think we have to rely on Docker images for now.
