### ISSUE TITLE
Proper procedure for handling updates to Synergia (and other codes) in the Jupyter container

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#77]
Although Synergia3.0 has not yet been released, the development team continues to put out incremental updates to the development branch of Synergia2. Some of these updates have made significant changes to the API. For example, the bunch constructor was recently [updated](https://cdcvs.fnal.gov/redmine/projects/synergia2/repository/revisions/077b99d7edf3f80033adb81ddbb755784e2dea54), making some of our rssynergia code incompatible. I have since updated our [rssynergia](https://github.com/radiasoft/rssynergia/commit/e8c6cbc08972cfa838c63964b245cffd41d08a04) code in a way that should preserve backwards compatibility.

This episode raises the question of how we want to manage updates to the less mature scientific codes in our containers, especially when unexpected API changes may cause headaches for users.

**Comment by robnagler** [comment]
Excellent. I was just thinking about this. :)

radiasoft/devops#56, radiasoft/containers#65, and radiasoft/containers#64 will address this in part. In order to initiate the builds of the docker image, we would probably require a checkin, since Travis has to bind its webhooks to a single repository.

What we should do is have a test script in rssynergia that will be run with the beamsim build that will test the basic API to make sure changes don't break anything. Would be good to have this for rswarp as well.

I'm finishing up my poster (hopefully) and then I'll get to work on some of these problems.

**Comment by robnagler** [comment]
The automated builds seem to alleviate some of the pain here. Should we close this Issue?

**Comment by ncook882** [comment]
I think it's OK to close this for now, but perhaps we should create new issues related to generating test scripts for rswarp and rssynergia as suggested above.

**Comment by robnagler** [comment]
We could create those in rswarp and rssynergia.  There's still radiasoft/containers#3: test codes in build. If we could run "python setup.py test" for a few codes, it would be a good thing. :)
