### ISSUE TITLE
build Warp/PICSAR on Cori at NERSC

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/devops#97]
This is important but is not funded by any active projects, so charge time to Science Support or Tech Support.

Warp can use a new highly-optimized physics kernel called PICSAR.
After it has been built and tested on Edison, we need to do the same on Cori, which uses the manycore KNL processors from Intel. Warp/PICSAR are reported by LBL to work well on this processor.

The Warp source is here (as we all know):
https://bitbucket.org/berkeleylab/warp

The PICSAR home page is here:
https://picsar.net/

The Bitbucket repository is not yet open (will be soon, I hear), but if you send them your Bitbucket username, then they will give you read access.

**Comment by robnagler** [comment]
I have a script, which seems to work on Cori. You can select whether it is a KNL or Haswell. 

What I don't know is how you want it delivered. It could be something like:

```
curl radia.run | bash -s picsar [knl]
```

This would install warp-picsar in a fixed location in $SCRATCH. This doesn't seem right to me. We should maybe install in ~/.local/{lib,bin}. I might be able to get it to work with a virtualenv, but that doesn't seem to be the way people work. It's a pseudo-virtualenv by setting $PYTHONPATH.

I'm pretty sure the script would work on Edison, too, but I don't see that as a necessary step since the point of this is to run KNL afaict.

LMK how you want it delivered.

**Comment by bruhwiler** [comment]
Awesome!

I think a fixed location in $SCRATCH is the right choice.
$HOME is a very limited resource and is slow to access from the compute nodes.
$SCRATCH always has the fastest I/O which is important for instantiation.

It would be helpful to have it work in the same way on Edison.
PICSAR has new/improved algorithms and is faster in general than the original Warp.

**Comment by robnagler** [comment]
This works for me:

```
curl radia.run | bash -s warp
```

It will compile only on Cori right now. I can test on Edison once we know we want this approach. If you run the command in your Linux box, it'll do the standard, non-PICSAR install.You need access to the PICSAR repo so you'll need to enter your bitbucket credentials or set them up in advance in your netrc.
