### ISSUE TITLE
Update Synergia and chef on Jupyter for impedance calculations

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#98]
Alex Macridin has updated Synergia with new features for simulating impedance. I'd like to be able to verify his simulations on Jupyter. See the most recent commit ([02c2e941](https://cdcvs.fnal.gov/redmine/projects/synergia2/repository/revisions/02c2e941de93ae511f68db31daf70e4c69863534)) on the `devel` branch of Synergia is June 8, 2017.

Additionally, Eric Stern has updated the `devel-synergia` branch of chef (commit [b593e2af](https://cdcvs.fnal.gov/redmine/projects/accelerator-modeling/repository?utf8=%E2%9C%93&rev=devel-synergia)) to correctly compute tunes in the vertical plane when using a lattice with the nonlinear insert. This would also be a helpful fix to have in place.

**Comment by robnagler** [comment]
I'm rebuilding now. It'll take a few hours before deploy happens.

**Comment by robnagler** [comment]
The build is failing for dependency issues. I need to debug tomorrow.

**Comment by robnagler** [comment]
bnlcrl is including pandas which hardcodes Sphinx==1.3.5. Talking with @mrakitin about the issue.

**Comment by mrakitin** [comment]
@robnagler, I updated the bnlcrl as you suggested - moved the plotting part along with Pandas/NumPy/Matplotlib imports to a separate module (https://github.com/mrakitin/bnlcrl/commit/e9d012029ab66d790e6bacbfe735cf4ed6221fea). I suspect it may still be failing due to pandas is in [requirements.txt](https://github.com/mrakitin/bnlcrl/blob/master/requirements.txt#L4). Please suggest what to do next.

**Comment by robnagler** [comment]
The latest image contains the synergia 36563ade162b35cbc899bf1f5177a88e3e412646

Just restart your JupyterHub server or download radiasosft/beamsim-jupyter:alpha.
